# Generated by Django 5.2.5 on 2025-08-21 00:35

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('crafts', 'Crafts'), ('music', 'Music'), ('food', 'Food'), ('rituals', 'Rituals')], max_length=20)),
                ('image_url', models.URLField()),
                ('vr_images', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, size=None)),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('visit_count', models.PositiveIntegerField(default=0)),
                ('experience_duration', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIStory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('historical', 'Historical'), ('cultural', 'Cultural'), ('personal', 'Personal')], max_length=20)),
                ('personalized_for', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_stories', to='villages.village')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
