# Generated by Django 5.2.5 on 2025-09-18 10:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_alter_order_options_order_paid_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(13), django.core.validators.MaxValueValidator(120)])),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('non_binary', 'Non-binary'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('country', models.CharField(choices=[('ZA', 'South Africa'), ('BW', 'Botswana'), ('NA', 'Namibia'), ('ZW', 'Zimbabwe'), ('ZM', 'Zambia'), ('MZ', 'Mozambique'), ('SZ', 'Eswatini'), ('LS', 'Lesotho'), ('OTHER', 'Other')], default='ZA', max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('interests', models.TextField(blank=True, help_text='Tell us about your interests in South African culture, history, or tourism')),
                ('how_did_you_hear', models.CharField(blank=True, help_text='How did you hear about Roots to Realities?', max_length=200)),
                ('marketing_consent', models.BooleanField(default=False, help_text='I agree to receive marketing communications')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
